#
# Protectplanet importer cronjob
#

name: planet

#
# Run every first of the month
#

on:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - run: go build cron/planet/countries/importer.go
      - run: ./importer
      - run: go build cron/planet/areas/importer.go
      - run: ./importer

